# 2013-10-12 07:56 (cc) <paul4hough@gmail.com>

language: c
notifications:
  email:
    - paul4hough@gmail.com

before_script:
  - echo -e "Host heroku.com StrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "Host github.com StrictHostKeyChecking no\n" >> ~/.ssh/config
  - uname -a
  - autoconf --version
  - env

script:
  - autoreconf
  - ./configure
  - make check
  - make install
